name: "Update CA Bundles"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "18 18 * * *"

permissions:
  packages: read
  contents: write

jobs:
  update:
    name: "Update"
    runs-on: ubuntu-latest
    steps:
      - name: Generate Tag Name
        id: tag_name
        run: |
          echo "TAG_NAME=$(date +'bundle_%Y%m%d')" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # pin@v4.1.0
      - name: Update CA Bundles
        id: update_bundles
        uses: docker://ghcr.io/tls-inspector/rootca:latest
        env:
          ROOTCA_SIGNING_PRIVATE_KEY: ${{ secrets.ROOTCA_SIGNING_PRIVATE_KEY }}
          ROOTCA_SIGNING_PUBLIC_KEY: ${{ secrets.ROOTCA_SIGNING_PUBLIC_KEY }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # pin@v4.16.0
        with:
          commit_user_name: Ian Spence
          commit_user_email: ian@ecnepsnai.com
          commit_author: Ian Spence <ian@ecnepsnai.com>
          commit_message: "[Actions] Update CA Bundles"
          tagging_message: "${{ env.TAG_NAME}}"
      - name: Make Release If Needed
        id: release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v0.1.15
        if: steps.commit.outputs.changes_detected == 'true'
        with:
          name: ${{ env.TAG_NAME}} - CA Bundles
          target_commitish: ${{ steps.commit.commit_hash }}
          tag_name: "${{ env.TAG_NAME}}"
          body: Automatic CA bundle update
          files: |
            bundles/bundle_metadata.json
            bundles/bundle_metadata.json.sig
            bundles/apple_ca_bundle.p7b
            bundles/apple_ca_bundle.p7b.sig
            bundles/apple_ca_bundle.pem
            bundles/apple_ca_bundle.pem.sig
            bundles/google_ca_bundle.p7b
            bundles/google_ca_bundle.p7b.sig
            bundles/google_ca_bundle.pem
            bundles/google_ca_bundle.pem.sig
            bundles/microsoft_ca_bundle.p7b
            bundles/microsoft_ca_bundle.p7b.sig
            bundles/microsoft_ca_bundle.pem
            bundles/microsoft_ca_bundle.pem.sig
            bundles/mozilla_ca_bundle.p7b
            bundles/mozilla_ca_bundle.p7b.sig
            bundles/mozilla_ca_bundle.pem
            bundles/mozilla_ca_bundle.pem.sig
            bundles/tlsinspector_ca_bundle.p7b
            bundles/tlsinspector_ca_bundle.p7b.sig
            bundles/tlsinspector_ca_bundle.pem
            bundles/tlsinspector_ca_bundle.pem.sig
            bundles/signing_key.pem
            bundles/certificates.csv
