name: "Update Mozilla CA Bundle"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "25 8 * * 1"

permissions:
  packages: read
  contents: write

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Tag Name
        id: tag_name
        run: echo "TAG_NAME=$(date +'moz_ca_%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
      - name: Update Mozilla CA Bundle
        id: update_bundle
        uses: docker://ghcr.io/tls-inspector/rootca:latest
      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@0b007fbd1180b8e3a3668b21c6517392fe8f26eb # pin@v4
        with:
          commit_user_name: Ian Spence
          commit_user_email: ian@ecnepsnai.com
          commit_author: Ian Spence <ian@ecnepsnai.com>
          commit_message: Update Mozilla CA Bundle
          tagging_message: "${{ env.TAG_NAME}}"
      - name: Make Release
        id: release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
        if: steps.commit.outputs.changes_detected == 'true'
        with:
          name: "Mozilla CA Bundle ${{ github.event.repository.updated_at}}"
          body: "Generated by workflow ${{ env.GITHUB_WORKFLOW }} on ${{ github.event.repository.updated_at}}"
          target_commitish: ${{ steps.commit.commit_hash }}
          tag_name: "${{ env.TAG_NAME}}"
          files: |
            BundleMetadata.plist
            moz_ca_bundle.p7b
