name: "Update CA Bundle"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "25 8 * * 1"

permissions:
  packages: read
  contents: write

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Tag Name
        id: tag_name
        run: echo "TAG_NAME=$(date +'bundle_%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3.2.0
      - name: Update CA Bundle
        id: update_bundle
        uses: docker://ghcr.io/tls-inspector/rootca:latest
        env:
          ROOTCA_SIGNING_PRIVATE_KEY: ${{ secrets.ROOTCA_SIGNING_PRIVATE_KEY }}
          ROOTCA_SIGNING_PUBLIC_KEY: ${{ secrets.ROOTCA_SIGNING_PUBLIC_KEY }}
      - name: Commit Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # pin@v4
        with:
          commit_user_name: Ian Spence
          commit_user_email: ian@ecnepsnai.com
          commit_author: Ian Spence <ian@ecnepsnai.com>
          commit_message: Update CA Bundle
          tagging_message: "${{ env.TAG_NAME}}"
      - name: Make Release
        id: release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
        if: steps.commit.outputs.changes_detected == 'true'
        with:
          name: CA Bundle ${{ github.event.repository.updated_at}}
          target_commitish: ${{ steps.commit.commit_hash }}
          tag_name: "${{ env.TAG_NAME}}"
          files: |
            bundle_metadata.json
            bundle_metadata.json.sig
            mozilla_ca_bundle.p7b
            mozilla_ca_bundle.p7b.sig
            microsoft_ca_bundle.p7b
            microsoft_ca_bundle.p7b.sig
            google_ca_bundle.p7b
            google_ca_bundle.p7b.sig
            signing_key.pem
            certificates.csv
